from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
import json
from pathlib import Path
import shutil
import subprocess
import sys
import time
from typing import Any


CONDITIONS: dict[str, list[str]] = {
    "sac": [],
    "sac_official_opt": [
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "sac_redo_0025": [
        "--redo-interval-updates",
        "2000",
        "--redo-dormant-threshold",
        "0.025",
    ],
    "sac_redo_01": [
        "--redo-interval-updates",
        "2000",
        "--redo-dormant-threshold",
        "0.1",
    ],
    "sac_swd": [
        "--swd-linear-decay-steps",
        "80000",
        "--swd-min-weight",
        "0.1",
    ],
    "sac_hard_reset_05": [
        "--pendulum-hard-reset-prob",
        "0.5",
        "--pendulum-hard-reset-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-reset-abs-theta-high",
        "2.356194490192345",
        "--pendulum-hard-reset-velocity-limit",
        "1.0",
    ],
    "simba_backbone": [
        "--simba-backbone",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
    ],
    "simba_backbone_official_opt": [
        "--simba-backbone",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_backbone_no_feature_norm": [
        "--simba-backbone",
        "--simba-no-feature-norm",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
    ],
    "simba_backbone_no_observation_norm": [
        "--simba-backbone",
        "--simba-no-observation-norm",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
    ],
    "simba_projection": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
    ],
    "simba_projection_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_no_feature_norm": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-no-feature-norm",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
    ],
    "simba_reward_scaling_official_opt": [
        "--simba-backbone",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_distributional_official_opt": [
        "--simba-backbone",
        "--simba-distributional-critic",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
    ],
    "simba_full_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_official_opt_sacn16": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "16",
        "--sacn-importance-quantile",
        "0.75",
    ],
    "simba_full_official_opt_sacn16_recent_ess": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "16",
        "--sacn-importance-quantile",
        "0.75",
        "--sacn-recent-max-age-steps",
        "10000",
        "--sacn-min-horizon-ess-fraction",
        "0.2",
    ],
    "simba_full_official_opt_sacn32_recent_ess": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "32",
        "--sacn-importance-quantile",
        "0.75",
        "--sacn-recent-max-age-steps",
        "10000",
        "--sacn-min-horizon-ess-fraction",
        "0.2",
    ],
    "simba_full_official_opt_sacn64_recent_ess": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "64",
        "--sacn-importance-quantile",
        "0.75",
        "--sacn-recent-max-age-steps",
        "10000",
        "--sacn-min-horizon-ess-fraction",
        "0.2",
    ],
    "simba_full_official_opt_tsacn16": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "16",
        "--sacn-importance-mode",
        "none",
        "--sacn-non-soft-targets",
        "--sacn-no-tau-entropy",
    ],
    "simba_full_official_opt_nois_sacn8_soft": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "8",
        "--sacn-importance-mode",
        "none",
    ],
    "simba_full_official_opt_nois_sacn8_soft_stop10k": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "8",
        "--sacn-importance-mode",
        "none",
        "--sacn-stop-after-steps",
        "10000",
    ],
    "simba_full_official_opt_nois_sacn8_soft_stop25k": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "8",
        "--sacn-importance-mode",
        "none",
        "--sacn-stop-after-steps",
        "25000",
    ],
    "simba_full_official_opt_nois_sacn16_soft": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "16",
        "--sacn-importance-mode",
        "none",
    ],
    "simba_full_official_opt_ref_interleave_nois_sacn8_soft": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "8",
        "--sacn-importance-mode",
        "none",
        "--reference-guidance-mode",
        "interleaved_execution",
        "--reference-guidance-policy",
        "best",
        "--reference-guidance-probability",
        "0.2",
    ],
    "simba_full_official_opt_ref_interleave_nois_sacn16_soft": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "16",
        "--sacn-importance-mode",
        "none",
        "--reference-guidance-mode",
        "interleaved_execution",
        "--reference-guidance-policy",
        "best",
        "--reference-guidance-probability",
        "0.2",
    ],
    "simba_full_official_opt_tsacn32": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "32",
        "--sacn-importance-mode",
        "none",
        "--sacn-non-soft-targets",
        "--sacn-no-tau-entropy",
    ],
    "simba_full_official_opt_tsacn64": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "64",
        "--sacn-importance-mode",
        "none",
        "--sacn-non-soft-targets",
        "--sacn-no-tau-entropy",
    ],
    "simba_full_official_opt_tsacn32_hard": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "32",
        "--sacn-importance-mode",
        "none",
        "--sacn-non-soft-targets",
        "--sacn-no-tau-entropy",
        "--pendulum-hard-replay-fraction",
        "0.2",
        "--pendulum-hard-replay-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-replay-abs-theta-high",
        "3.141592653589793",
        "--pendulum-hard-replay-velocity-limit",
        "1.0",
    ],
    "simba_full_official_opt_sacn32_hard_recent_ess": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "32",
        "--sacn-importance-quantile",
        "0.75",
        "--sacn-recent-max-age-steps",
        "10000",
        "--sacn-min-horizon-ess-fraction",
        "0.2",
        "--pendulum-hard-replay-fraction",
        "0.2",
        "--pendulum-hard-replay-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-replay-abs-theta-high",
        "3.141592653589793",
        "--pendulum-hard-replay-velocity-limit",
        "1.0",
    ],
    "simba_full_hard_reset_02_official_opt_sacn32_recent_ess": [
        "--pendulum-hard-reset-prob",
        "0.2",
        "--pendulum-hard-reset-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-reset-abs-theta-high",
        "2.356194490192345",
        "--pendulum-hard-reset-velocity-limit",
        "1.0",
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--sacn-n-step",
        "32",
        "--sacn-importance-quantile",
        "0.75",
        "--sacn-recent-max-age-steps",
        "10000",
        "--sacn-min-horizon-ess-fraction",
        "0.2",
    ],
    "simba_full_official_opt_sacn32_entropy_recent_ess": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.03",
        "--target-entropy-scale",
        "-1.0",
        "--sacn-n-step",
        "32",
        "--sacn-importance-quantile",
        "0.75",
        "--sacn-recent-max-age-steps",
        "10000",
        "--sacn-min-horizon-ess-fraction",
        "0.2",
    ],
    "simba_full_official_opt_dp_qbc": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--reference-auxiliary-mode",
        "q_filtered_bc",
        "--reference-auxiliary-policy",
        "dp",
        "--reference-auxiliary-weight",
        "0.05",
    ],
    "simba_full_official_opt_redo": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--redo-interval-updates",
        "2000",
        "--redo-dormant-threshold",
        "0.025",
    ],
    "simba_full_official_opt_swd": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
        "--swd-linear-decay-steps",
        "80000",
        "--swd-min-weight",
        "0.1",
    ],
    "simba_full_hard_reset_02_official_opt": [
        "--pendulum-hard-reset-prob",
        "0.2",
        "--pendulum-hard-reset-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-reset-abs-theta-high",
        "2.356194490192345",
        "--pendulum-hard-reset-velocity-limit",
        "1.0",
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_hard_replay_02_official_opt": [
        "--pendulum-hard-replay-fraction",
        "0.2",
        "--pendulum-hard-replay-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-replay-abs-theta-high",
        "2.356194490192345",
        "--pendulum-hard-replay-velocity-limit",
        "1.0",
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_hard_reset_01_official_opt": [
        "--pendulum-hard-reset-prob",
        "0.1",
        "--pendulum-hard-reset-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-reset-abs-theta-high",
        "2.356194490192345",
        "--pendulum-hard-reset-velocity-limit",
        "1.0",
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "sac_gamma_0975": [
        "--gamma",
        "0.975",
    ],
    "simba_backbone_real_defaults_official_gamma": [
        "--simba-backbone",
        "--gamma",
        "0.975",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_real_defaults_official_gamma": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--gamma",
        "0.975",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_distributional_real_defaults_official_gamma": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-reward-scaling",
        "--gamma",
        "0.975",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_reward_scaling_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_distributional_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_distributional_hard_reset_05_official_opt": [
        "--pendulum-hard-reset-prob",
        "0.5",
        "--pendulum-hard-reset-abs-theta-low",
        "2.0943951023931953",
        "--pendulum-hard-reset-abs-theta-high",
        "2.356194490192345",
        "--pendulum-hard-reset-velocity-limit",
        "1.0",
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_feature_norm_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-no-feature-norm",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_observation_norm_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-no-observation-norm",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_input_shift_official_opt": [
        "--simba-backbone",
        "--simba-weight-projection",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-no-input-shift",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
    "simba_full_no_projection_official_opt": [
        "--simba-backbone",
        "--simba-distributional-critic",
        "--simba-reward-scaling",
        "--simba-actor-hidden-dim",
        "32",
        "--simba-critic-hidden-dim",
        "64",
        "--simba-critic-num-bins",
        "51",
        "--policy-lr",
        "1e-4",
        "--q-lr",
        "1e-4",
        "--policy-lr-final",
        "5e-5",
        "--q-lr-final",
        "5e-5",
        "--alpha-initial-value",
        "0.01",
        "--target-entropy-scale",
        "-0.5",
    ],
}


def main() -> None:
    args = parse_args()
    run_root = Path(args.run_root).resolve()
    report_root = Path(args.report_root).resolve()
    log_root = report_root / "logs"
    log_root.mkdir(parents=True, exist_ok=True)
    manifest_path = report_root / "manifest.jsonl"

    selected_conditions = args.conditions or list(CONDITIONS)
    jobs = [
        {
            "condition": condition,
            "seed": seed,
            "run_dir": run_root / condition / f"seed{seed}",
            "extra_args": CONDITIONS[condition],
        }
        for condition in selected_conditions
        for seed in args.seeds
    ]

    results: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=args.max_workers) as pool:
        futures = [pool.submit(run_job, job, args, run_root, log_root) for job in jobs]
        for future in as_completed(futures):
            result = future.result()
            results.append(result)
            with manifest_path.open("a", encoding="utf-8") as f:
                f.write(json.dumps(result, sort_keys=True) + "\n")
            print(json.dumps(result, sort_keys=True), flush=True)

    summary = summarize(results)
    (report_root / "pilot_run_summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
    if any(result["status"] != "completed" for result in results):
        raise SystemExit(1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Week 3 Pendulum SimbaV2 pilot ablations.")
    parser.add_argument("--config", default="configs/week1_pendulum.json")
    parser.add_argument("--run-root", default="runs/week3_simbav2_pilot_10k")
    parser.add_argument("--report-root", default="reports/week3_simbav2_pilot_10k")
    parser.add_argument("--conditions", nargs="*", choices=sorted(CONDITIONS))
    parser.add_argument("--seeds", nargs="+", type=int, default=[0, 1, 2])
    parser.add_argument("--max-workers", type=int, default=2)
    parser.add_argument("--total-steps", type=int, default=10_000)
    parser.add_argument("--learning-starts", type=int, default=1_000)
    parser.add_argument("--buffer-size", type=int, default=50_000)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--updates-per-step", type=int, default=1)
    parser.add_argument("--eval-episodes", type=int, default=50)
    parser.add_argument("--log-interval", type=int, default=None)
    parser.add_argument("--replay-inspection-interval", type=int, default=None)
    parser.add_argument("--diagnostics-interval", type=int, default=None)
    parser.add_argument(
        "--full-update-diagnostics",
        action="store_true",
        help="Keep per-update parameter, feature, and gradient norm telemetry enabled.",
    )
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--overwrite-incomplete", action="store_true")
    return parser.parse_args()


def run_job(job: dict[str, Any], args: argparse.Namespace, run_root: Path, log_root: Path) -> dict[str, Any]:
    condition = job["condition"]
    seed = int(job["seed"])
    run_dir = Path(job["run_dir"])
    if completed_run(run_dir, args.total_steps):
        return result_for(job, "completed", 0, "already complete", 0.0)
    if run_dir.exists():
        if not args.overwrite_incomplete:
            return result_for(job, "skipped_incomplete", 0, "run exists but is incomplete", 0.0)
        resolved = run_dir.resolve()
        if run_root not in resolved.parents:
            raise ValueError(f"Refusing to delete run outside {run_root}: {resolved}")
        shutil.rmtree(resolved)

    stdout_path = log_root / f"{condition}_seed{seed}.stdout.log"
    stderr_path = log_root / f"{condition}_seed{seed}.stderr.log"
    command = [
        sys.executable,
        "-m",
        "last_nine_rl.train",
        "--config",
        args.config,
        "--run-dir",
        str(run_dir),
        "--seed",
        str(seed),
        "--total-steps",
        str(args.total_steps),
        "--learning-starts",
        str(args.learning_starts),
        "--buffer-size",
        str(args.buffer_size),
        "--batch-size",
        str(args.batch_size),
        "--updates-per-step",
        str(args.updates_per_step),
        "--eval-every-steps",
        str(args.total_steps),
        "--eval-episodes",
        str(args.eval_episodes),
        "--log-interval",
        str(args.log_interval or args.total_steps),
        "--replay-inspection-interval",
        str(args.replay_inspection_interval or args.total_steps),
        "--diagnostics-interval",
        str(args.diagnostics_interval or args.total_steps),
        "--save-replay",
        "--device",
        args.device,
        "--overwrite",
        *job["extra_args"],
    ]
    if not args.full_update_diagnostics:
        command.insert(command.index("--device"), "--fast-updates")
    env = {
        **dict(**__import__("os").environ),
        "OMP_NUM_THREADS": "1",
        "MKL_NUM_THREADS": "1",
        "NUMEXPR_NUM_THREADS": "1",
    }
    start = time.time()
    with stdout_path.open("w", encoding="utf-8") as stdout, stderr_path.open("w", encoding="utf-8") as stderr:
        proc = subprocess.run(command, cwd=Path.cwd(), env=env, stdout=stdout, stderr=stderr, check=False)
    duration = time.time() - start
    status = "completed" if proc.returncode == 0 and completed_run(run_dir, args.total_steps) else "failed"
    return result_for(job, status, proc.returncode, " ".join(command), duration)


def result_for(job: dict[str, Any], status: str, returncode: int, command: str, duration_s: float) -> dict[str, Any]:
    run_dir = Path(job["run_dir"])
    final_eval = final_evaluation(run_dir)
    return {
        "condition": job["condition"],
        "seed": int(job["seed"]),
        "status": status,
        "returncode": int(returncode),
        "duration_s": float(duration_s),
        "run_dir": str(run_dir),
        "command": command,
        "complete": completed_run(run_dir),
        "has_replay": (run_dir / "replay_final.npz").is_file(),
        "has_checkpoint": (run_dir / "checkpoints" / "final.pt").is_file(),
        "final_eval": final_eval,
    }


def completed_run(run_dir: Path, total_steps: int | None = None) -> bool:
    for event in read_events(run_dir):
        if event.get("type") == "run_complete" and (total_steps is None or int(event.get("step", -1)) == int(total_steps)):
            return True
    return False


def final_evaluation(run_dir: Path) -> dict[str, Any]:
    evaluations = [event for event in read_events(run_dir) if event.get("type") == "evaluation"]
    if not evaluations:
        return {}
    event = evaluations[-1]
    return {"step": event.get("step"), **event.get("payload", {})}


def read_events(run_dir: Path) -> list[dict[str, Any]]:
    path = run_dir / "events.jsonl"
    if not path.exists():
        return []
    events = []
    with path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return events


def summarize(results: list[dict[str, Any]]) -> dict[str, Any]:
    by_condition: dict[str, list[dict[str, Any]]] = {}
    for result in results:
        by_condition.setdefault(result["condition"], []).append(result)
    out: dict[str, Any] = {}
    for condition, items in sorted(by_condition.items()):
        completed = [item for item in items if item["status"] == "completed"]
        returns = [
            float(item["final_eval"]["mean_return"])
            for item in completed
            if item.get("final_eval") and "mean_return" in item["final_eval"]
        ]
        strict = [
            float(item["final_eval"]["strict_success_rate"])
            for item in completed
            if item.get("final_eval") and "strict_success_rate" in item["final_eval"]
        ]
        out[condition] = {
            "num_jobs": len(items),
            "num_completed": len(completed),
            "num_replays": sum(1 for item in completed if item["has_replay"]),
            "mean_return_mean": sum(returns) / len(returns) if returns else None,
            "strict_success_rate_mean": sum(strict) / len(strict) if strict else None,
            "runs": items,
        }
    return out


if __name__ == "__main__":
    main()
